name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and push Docker image
      run: docker-compose up --build

    - name: Run formatter
      run: docker-compose run formatter

    - name: Run linter
      run: docker-compose run linter

    - name: Run tests
      run: docker-compose run test